# Generated by Django 5.1.6 on 2026-01-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_status_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('PA', 'Paid'), ('D', 'Done'), ('M', 'Missed'), ('C', 'Cancelled'), ('DE', 'Delayed')], default='PE', max_length=50),
        ),
    ]
