# Generated by Django 5.1.6 on 2026-01-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_remove_appointment_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('PA', 'Paid'), ('D', 'Done'), ('M', 'Missed'), ('C', 'Cancelled')], default='PE', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
