# Generated by Django 5.1.6 on 2026-01-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0008_alter_appointment_status_alter_payment_payment_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("manual", "Manual")],
                default="stripe",
                max_length=20,
            ),
        ),
    ]
