# Generated by Django 5.1.6 on 2026-01-25 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0009_alter_payment_payment_type"),
        ("doctors", "0018_specialty_name_ar"),
        ("patients", "0003_rename_title_patientfile_name_patientfile_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientSharedFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sharing_type",
                    models.CharField(
                        choices=[("DOCTOR", "Doctor"), ("APPOINTMENT", "Appointment")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_folders",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_folders",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_entries",
                        to="patients.patientfolder",
                    ),
                ),
            ],
        ),
    ]
