# Generated by Django 5.1.6 on 2026-01-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_alter_doctor_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='reviewers_num',
            field=models.IntegerField(default=0),
        ),
    ]
