# Generated by Django 5.1.6 on 2026-01-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0017_patientreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="name_ar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
